<?php

namespace Database\Seeders;

use App\Models\Exercise;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ExerciseSeeder extends Seeder
{
    public function run(): void
    {
        foreach ($this->exercises() as $e) {
            Exercise::updateOrCreate(['slug' => Str::slug($e[0])], [
                'name' => $e[0],
                'muscle_group' => $e[1],
                'difficulty' => $e[2],
                'equipment' => $e[3],
                'description' => $e[4],
                'instructions' => implode("\n", $e[5]),
                'target_muscles' => $e[6],
                'tips' => $e[7],
                'default_sets' => $e[8],
                'default_reps' => $e[9],
                'default_rest_seconds' => $e[10],
                'image' => 'images/exercises/'.$e[1].'.svg',
                'status' => 'active',
            ]);
        }
    }

    /**
     * [name, muscle_group, difficulty, equipment, description, steps[], target_muscles, tips, sets, reps, rest]
     */
    private function exercises(): array
    {
        return [
            // ---------------- Chest ----------------
            ['Bench Press', 'chest', 'intermediate', 'Barbell, ghế phẳng',
                'Bài tập compound kinh điển phát triển sức mạnh và kích thước cơ ngực, đồng thời tác động vai trước và tay sau.',
                ['Nằm ngửa trên ghế phẳng, mắt thẳng dưới thanh đòn, hai bàn chân đặt chắc trên sàn.',
                    'Nắm thanh đòn rộng hơn vai một chút, siết bả vai về sau và xuống dưới.',
                    'Nhấc thanh đòn khỏi giá, giữ thẳng tay phía trên ngực.',
                    'Hít vào, hạ thanh đòn có kiểm soát xuống giữa ngực.',
                    'Thở ra, đẩy mạnh thanh đòn lên về vị trí ban đầu.'],
                'Ngực giữa, Vai trước, Tay sau',
                'Không nảy thanh đòn trên ngực. Giữ cổ tay thẳng, khuỷu tay khoảng 45–70° so với thân. Nên có người hỗ trợ khi tập nặng.',
                4, '8-10', 90],
            ['Incline Dumbbell Press', 'chest', 'intermediate', 'Dumbbell, ghế dốc',
                'Biến thể đẩy ngực trên ghế dốc 30–45°, tập trung vào phần ngực trên.',
                ['Chỉnh ghế dốc 30–45°, ngồi tựa lưng, mỗi tay cầm một quả tạ đơn.',
                    'Đưa tạ lên ngang vai, lòng bàn tay hướng về phía trước.',
                    'Đẩy tạ thẳng lên trên cho đến khi gần duỗi thẳng tay.',
                    'Hạ tạ chậm về ngang ngực trên, cảm nhận cơ ngực giãn.'],
                'Ngực trên, Vai trước, Tay sau',
                'Không để hai quả tạ va vào nhau ở đỉnh. Không chỉnh ghế quá dốc vì sẽ chuyển trọng tâm sang vai.',
                3, '10-12', 60],
            ['Push Up', 'chest', 'beginner', 'Không cần dụng cụ',
                'Bài tập với trọng lượng cơ thể, dễ thực hiện ở mọi nơi, giúp tăng sức bền ngực và core.',
                ['Chống hai tay xuống sàn rộng hơn vai, thân người thẳng từ đầu đến gót.',
                    'Siết cơ bụng và mông để giữ thân ổn định.',
                    'Hạ người xuống đến khi ngực gần chạm sàn.',
                    'Đẩy người lên về vị trí ban đầu.'],
                'Ngực, Tay sau, Vai trước, Core',
                'Không võng lưng hoặc chổng mông. Người mới có thể chống gối để giảm độ khó.',
                3, '12-15', 60],
            ['Chest Fly', 'chest', 'beginner', 'Dumbbell hoặc máy Pec Deck',
                'Bài tập cô lập giúp kéo giãn và siết cơ ngực, bổ trợ cho các bài đẩy.',
                ['Nằm trên ghế phẳng, hai tay cầm tạ đơn đưa thẳng lên trên ngực.',
                    'Hơi khuỵu khuỷu tay, mở rộng hai tay sang hai bên theo hình vòng cung.',
                    'Hạ đến khi cảm thấy ngực căng giãn.',
                    'Khép tay lại theo đường vòng cung, siết ngực ở đỉnh.'],
                'Ngực giữa, Vai trước',
                'Dùng mức tạ vừa phải, giữ góc khuỷu tay cố định trong suốt chuyển động.',
                3, '12-15', 60],

            // ---------------- Back ----------------
            ['Pull Up', 'back', 'advanced', 'Xà đơn',
                'Bài kéo xà phát triển cơ lưng xô, tạo độ rộng cho lưng và tăng sức mạnh thân trên.',
                ['Nắm xà rộng hơn vai, lòng bàn tay hướng ra ngoài.',
                    'Treo người thẳng tay, siết core.',
                    'Kéo người lên bằng cách hạ khuỷu tay xuống, đưa cằm vượt xà.',
                    'Hạ người chậm về vị trí treo ban đầu.'],
                'Lưng xô, Cơ tròn lớn, Tay trước',
                'Không đung đưa người lấy đà. Có thể dùng dây kháng lực hoặc máy hỗ trợ khi mới tập.',
                4, '6-8', 90],
            ['Lat Pulldown', 'back', 'beginner', 'Máy kéo cáp',
                'Bài kéo cáp từ trên xuống, thay thế Pull Up cho người mới, tập trung lưng xô.',
                ['Ngồi vào máy, chỉnh đệm giữ đùi vừa vặn.',
                    'Nắm thanh kéo rộng hơn vai.',
                    'Ưỡn ngực nhẹ, kéo thanh xuống ngang ngực trên.',
                    'Siết lưng 1 giây rồi trả thanh lên chậm.'],
                'Lưng xô, Cơ trám, Tay trước',
                'Không ngả người ra sau quá nhiều, không kéo thanh ra sau gáy.',
                3, '10-12', 60],
            ['Barbell Row', 'back', 'intermediate', 'Barbell',
                'Bài chèo tạ đòn giúp tăng độ dày lưng giữa và sức mạnh kéo.',
                ['Đứng rộng bằng hông, cầm thanh đòn rộng bằng vai.',
                    'Gập hông, đẩy mông ra sau, thân trên nghiêng khoảng 45°, lưng thẳng.',
                    'Kéo thanh đòn về phía bụng dưới, khép bả vai.',
                    'Hạ thanh đòn có kiểm soát.'],
                'Lưng giữa, Lưng xô, Cầu vai sau',
                'Giữ lưng trung tính, không giật người. Bắt đầu với mức tạ nhẹ để học kỹ thuật.',
                4, '8-10', 90],
            ['Deadlift', 'back', 'advanced', 'Barbell',
                'Bài compound toàn thân, phát triển sức mạnh chuỗi cơ sau: lưng dưới, mông, đùi sau.',
                ['Đứng hai chân rộng bằng hông, thanh đòn sát ống quyển.',
                    'Gập hông và gối, nắm thanh đòn ngay ngoài hai chân.',
                    'Ưỡn ngực, giữ lưng thẳng, siết lưng xô.',
                    'Đẩy chân xuống sàn, duỗi hông và gối để đứng thẳng.',
                    'Hạ thanh đòn theo đường thẳng sát chân về sàn.'],
                'Lưng dưới, Mông, Đùi sau, Cầu vai',
                'Tuyệt đối không cong lưng. Khởi động kỹ và tăng tạ từ từ.',
                3, '5', 120],

            // ---------------- Shoulders ----------------
            ['Shoulder Press', 'shoulders', 'intermediate', 'Dumbbell hoặc Barbell',
                'Bài đẩy vai qua đầu phát triển toàn bộ cơ vai, đặc biệt vai trước và vai giữa.',
                ['Ngồi hoặc đứng thẳng, cầm tạ ngang vai, lòng bàn tay hướng trước.',
                    'Siết core, đẩy tạ thẳng lên trên đầu.',
                    'Duỗi gần thẳng tay ở đỉnh.',
                    'Hạ tạ về ngang vai có kiểm soát.'],
                'Vai trước, Vai giữa, Tay sau',
                'Không ưỡn lưng dưới quá mức khi đẩy. Giữ cổ tay thẳng.',
                3, '10-12', 60],
            ['Lateral Raise', 'shoulders', 'beginner', 'Dumbbell',
                'Bài cô lập vai giữa, giúp vai rộng và tròn hơn.',
                ['Đứng thẳng, hai tay cầm tạ đơn ở hai bên hông.',
                    'Hơi khuỵu khuỷu, nâng tạ sang hai bên đến ngang vai.',
                    'Dừng 1 giây ở đỉnh.',
                    'Hạ tạ chậm về vị trí ban đầu.'],
                'Vai giữa',
                'Dùng tạ nhẹ, không nhún vai hay lắc người lấy đà.',
                3, '12-15', 45],
            ['Front Raise', 'shoulders', 'beginner', 'Dumbbell hoặc đĩa tạ',
                'Bài cô lập vai trước, bổ trợ cho các bài đẩy.',
                ['Đứng thẳng, cầm tạ trước đùi.',
                    'Nâng tạ thẳng phía trước đến ngang tầm mắt.',
                    'Hạ tạ chậm về vị trí ban đầu.'],
                'Vai trước',
                'Không ngả người ra sau. Có thể tập luân phiên từng tay.',
                3, '12', 45],

            // ---------------- Legs ----------------
            ['Squat', 'legs', 'intermediate', 'Barbell, khung squat',
                'Vua của các bài tập chân, phát triển đùi trước, mông và sức mạnh toàn thân.',
                ['Đặt thanh đòn trên cầu vai, hai chân rộng bằng vai, mũi chân hơi mở.',
                    'Hít sâu, siết core.',
                    'Đẩy hông ra sau và khuỵu gối, hạ người đến khi đùi song song sàn.',
                    'Đẩy gót chân xuống sàn để đứng lên.'],
                'Đùi trước, Mông, Đùi sau, Core',
                'Gối đi cùng hướng mũi chân, không để gối chụm vào trong. Giữ lưng thẳng.',
                4, '8-10', 120],
            ['Leg Press', 'legs', 'beginner', 'Máy đạp đùi',
                'Bài đạp đùi trên máy, an toàn cho người mới mà vẫn tải được mức tạ lớn.',
                ['Ngồi vào máy, lưng tựa sát đệm, đặt chân rộng bằng vai lên bàn đạp.',
                    'Mở khóa an toàn, hạ bàn đạp đến khi gối gập khoảng 90°.',
                    'Đạp mạnh bàn đạp lên, không khóa gối ở đỉnh.'],
                'Đùi trước, Mông',
                'Không để lưng dưới nhấc khỏi đệm khi hạ sâu.',
                3, '10-12', 90],
            ['Romanian Deadlift', 'legs', 'intermediate', 'Barbell hoặc Dumbbell',
                'Biến thể deadlift tập trung vào đùi sau và mông với chuyển động gập hông.',
                ['Đứng thẳng cầm thanh đòn trước đùi.',
                    'Hơi chùng gối, đẩy hông ra sau, hạ thanh đòn dọc theo chân.',
                    'Hạ đến khi đùi sau căng (khoảng giữa ống quyển).',
                    'Đẩy hông về trước để đứng thẳng, siết mông.'],
                'Đùi sau, Mông, Lưng dưới',
                'Lưng luôn thẳng, thanh đòn sát chân. Không hạ quá sâu nếu lưng bắt đầu cong.',
                3, '10', 90],
            ['Leg Extension', 'legs', 'beginner', 'Máy đá đùi',
                'Bài cô lập đùi trước trên máy.',
                ['Ngồi vào máy, đệm chân đặt trên cổ chân.',
                    'Duỗi thẳng chân, siết đùi trước ở đỉnh.',
                    'Hạ chậm về vị trí ban đầu.'],
                'Đùi trước',
                'Không dùng mức tạ quá nặng gây áp lực lên khớp gối.',
                3, '12-15', 60],

            // ---------------- Arms ----------------
            ['Bicep Curl', 'arms', 'beginner', 'Dumbbell hoặc Barbell',
                'Bài cuốn tạ cơ bản phát triển cơ tay trước.',
                ['Đứng thẳng, cầm tạ, lòng bàn tay hướng trước.',
                    'Giữ khuỷu tay sát thân, cuốn tạ lên ngang vai.',
                    'Siết tay trước ở đỉnh.',
                    'Hạ tạ chậm về vị trí ban đầu.'],
                'Tay trước',
                'Không đánh võng lưng hay đẩy khuỷu tay ra trước.',
                3, '10-12', 60],
            ['Hammer Curl', 'arms', 'beginner', 'Dumbbell',
                'Biến thể cuốn tạ cầm búa, tác động tay trước và cẳng tay.',
                ['Đứng thẳng, cầm tạ đơn, lòng bàn tay hướng vào thân.',
                    'Cuốn tạ lên, giữ nguyên hướng cầm.',
                    'Hạ tạ chậm về vị trí ban đầu.'],
                'Tay trước, Cơ cánh tay, Cẳng tay',
                'Có thể tập luân phiên hai tay để tập trung tốt hơn.',
                3, '10-12', 60],
            ['Tricep Pushdown', 'arms', 'beginner', 'Máy cáp',
                'Bài đẩy cáp xuống cô lập cơ tay sau.',
                ['Đứng trước máy cáp, nắm thanh hoặc dây thừng.',
                    'Khép khuỷu tay sát thân.',
                    'Đẩy thanh xuống đến khi duỗi thẳng tay.',
                    'Trả thanh lên chậm, khuỷu tay giữ cố định.'],
                'Tay sau',
                'Không dùng thân người đè xuống. Chỉ khuỷu tay chuyển động.',
                3, '12-15', 45],

            // ---------------- Core ----------------
            ['Plank', 'core', 'beginner', 'Thảm tập',
                'Bài giữ tĩnh tăng sức bền cơ core, hỗ trợ tư thế và các bài compound.',
                ['Chống cẳng tay xuống sàn, khuỷu tay dưới vai.',
                    'Duỗi thẳng chân, thân người thẳng từ đầu đến gót.',
                    'Siết bụng và mông, giữ tư thế theo thời gian quy định.'],
                'Cơ bụng, Core sâu, Lưng dưới',
                'Không võng lưng hay nhô mông. Thở đều. Reps tính theo giây.',
                3, '30-60', 45],
            ['Crunch', 'core', 'beginner', 'Thảm tập',
                'Bài gập bụng cơ bản tập trung cơ bụng trên.',
                ['Nằm ngửa, co gối, bàn chân đặt trên sàn.',
                    'Đặt tay sau đầu hoặc bắt chéo trước ngực.',
                    'Siết bụng, nâng vai khỏi sàn.',
                    'Hạ người chậm về vị trí ban đầu.'],
                'Cơ bụng trên',
                'Không kéo cổ bằng tay. Chuyển động nhỏ, tập trung siết bụng.',
                3, '15-20', 45],

            // ---------------- Cardio ----------------
            ['Jumping Jack', 'cardio', 'beginner', 'Không cần dụng cụ',
                'Bài cardio khởi động toàn thân, tăng nhịp tim nhanh.',
                ['Đứng thẳng, hai chân khép, tay để hai bên.',
                    'Bật nhảy dang rộng hai chân, đồng thời vung tay qua đầu.',
                    'Bật nhảy trở về tư thế ban đầu.',
                    'Lặp lại liên tục với nhịp đều.'],
                'Toàn thân, Bắp chân, Vai',
                'Tiếp đất nhẹ nhàng bằng mũi chân.',
                3, '30', 30],
            ['Burpee', 'cardio', 'intermediate', 'Không cần dụng cụ',
                'Bài cardio cường độ cao kết hợp squat, chống đẩy và bật nhảy.',
                ['Từ tư thế đứng, ngồi xổm và chống tay xuống sàn.',
                    'Bật hai chân ra sau về tư thế plank.',
                    'Thực hiện 1 lần chống đẩy (tùy chọn).',
                    'Thu chân về và bật nhảy lên cao, vỗ tay qua đầu.'],
                'Toàn thân, Đùi, Ngực, Core',
                'Giữ nhịp phù hợp với thể lực, ưu tiên kỹ thuật hơn tốc độ.',
                3, '10-15', 60],
            ['Mountain Climber', 'cardio', 'beginner', 'Không cần dụng cụ',
                'Bài leo núi tại chỗ giúp đốt calo và tăng sức bền core.',
                ['Vào tư thế plank cao, tay thẳng dưới vai.',
                    'Kéo gối phải về phía ngực rồi đổi chân nhanh.',
                    'Luân phiên hai chân liên tục.'],
                'Core, Vai, Đùi',
                'Giữ hông thấp, không nhấp nhô mông.',
                3, '30', 30],
        ];
    }
}
